version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./sources/wikidata.json:/web/sources/wikidata.json
    depends_on:
      postgres:
        condition: service_healthy
    
    env_file: .env.dev

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}"]
      interval: 2s
      timeout: 15s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
