version: '3.8'

services:
  test-runner:
    build:
      context: .
      dockerfile: web/TestDockerfile
    depends_on:
      postgres:
        condition: service_healthy

    env_file: .env.dev

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}"]
      interval: 30s
      timeout: 240s
      retries: 50
    volumes:
      - ./pgdata:/var/lib/postgresql/data
