name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
<<<<<<< HEAD
    defaults:
      run:
        working-directory: ./android-app
=======

>>>>>>> android-app/main
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check Formatting
        run: ./gradlew ktfmtCheck


      - name: Check Dependencies
        run: ./gradlew buildHealth

      - name: Build with Gradle
        run: ./gradlew build



