name: Deploy Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mkdocs:
    name: Build and deploy mkdocs site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./documentation
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    # run an ls command here for debugging purposes
    - name: List files
      run: ls -la

      
    - name: Build
      uses: jnanadarshan/mkdocs-build-action@v0.24



    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync output to S3
      run: |
        aws s3 sync ./site/ s3://documentation-site-mkdocs --delete